---
title: "Data Wrangling Exercise 2"
author: Faisal Mahmood
date: May 27, 2017
output: html_document
---


### Step 0: Load the data in RStudio

I uploaded the dataset into the data frame by saving it as a CSV file and entering the following code:
```
library(plyr)
library(dplyr)
library(tidyr)
setwd("~/Documents/Data Science Foundations/Data Wrangling")
titanic <- read.csv(file="~/Documents/Data Science Foundations/Data Wrangling/titanic_original.csv", header = TRUE, sep = ",", stringsAsFactors = FALSE)
titanic
```
This process also activated dplyr and tidyr. Now, by entering ```View(titanic)```, I can easily view the dataset.

### Step 1: Missing values for port of embarkation

I tallied the values of the ```embarked``` column, and then entered "S" into the blank entries. 
```
titanic %>% group_by(embarked) %>% tally()
titanic$embarked
titanic$embarked[which(titanic$embarked == "")] <- "S" 
titanic$embarked
titanic %>% group_by(embarked) %>% tally()
```

### Step 2: Missing values for age

I was instructed to calculate the mean of the ```age``` column based on the available data, and that use that value to fill in the missing value. The summary function easily gave me that info, and then I was able to plug the mean value into the missing slots.

```
summary(titanic$age)
titanic$age[which(is.na(titanic$age))] <- 29.8811
summary(titanic$age)
```

I also could have used the median age rather than the mean age, and perhaps that would have been better since the median cannot be skewed by outliers on either end of the distribution.

###Step 3: Missing values for lifeboat

I simply loaded the data for the ```boat``` column, and then filled the missing values with ```NA```.

```
titanic$boat
titanic$boat[which(titanic$boat == "")] <- NA
titanic$boat
```

###Step 4: Cabin Numbers

I loaded the data for the ```cabin``` column, and then filled the missing values with ```NA```. For me, it made sense because ```NA``` by definition means that there is no given value for that particular data point, and filling the missing values with ```NA``` enabled me to label those values ```0``` in the newly created ```has_cabin_number``` column. After that first step, the ```has_cabin_number``` column then had missing values for rows that had numbers in the ```cabin``` column. That made it easy for me to fill those missing values in the ```has_cabin_number``` column with ```1```. The ```has_cabin_number``` column was then complete.

```
titanic$cabin
titanic$cabin[which(titanic$cabin == "")] <- NA
titanic$has_cabin_number[which(is.na(titanic$cabin))] <- 0
titanic$has_cabin_number[which(is.na(titanic$has_cabin_number))] <- 1
titanic$has_cabin_number
```

###Step 5: Submit the project

I saved the cleaned ```titanic``` data as a new CSV file.

```
write.csv(titanic, "titanic_clean.csv")
```
